# Stage 1: Build the Native Executable
FROM quay.io/quarkus/ubi-quarkus-native-image:22.3-java17 AS builder

# Copy the application JAR and build artifacts into the container
WORKDIR /work
COPY target/*-runner /work/application

# Stage 2: Create the Final Image
FROM gcr.io/distroless/base-debian11

# Copy the native binary from the builder stage
COPY --from=builder /work/application /work/application

# Set the binary as the entrypoint
ENTRYPOINT ["/work/application"]
