# Source: Splunk HEC
[sources.splunk_hec]
type = "splunk_hec"
address = "0.0.0.0:8088" # Vector listens on port 8088 for logs
token = "vVVbUPkNeME00Zu6okzbN/zlqSZPGapNA4fhDwSjpNc=" # Token for HEC authentication

# Optional: Add metadata to incoming logs
[transforms.add_metadata]
type = "remap"
inputs = ["splunk_hec"]
source = '''
  .app = "ecs-service"
  .environment = "dev"
  encode_json(.)
'''

# Sink: Elasticsearch (or any desired destination)
[sinks.elasticsearch]
type = "elasticsearch"
inputs = ["add_metadata"]
endpoint = "http://elasticsearch:9200"
index = "{{ app }}-{{ environment }}-logs"
compression = "gzip"
bulk_action = "index"
