name: Deploy to ECS

on:
  workflow_dispatch:
    inputs:
      image_tag:
        description: "The tag of the container image to deploy"
        required: true

jobs:
  deploy:
    name: Deploy Quarkus App to ECS
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Output Task Definition
        run: |
          cat task-definitions/quarkus-app-task.json

      - name: Update Task Definition File with New Image
        run: |
          sed -i "s|:latest|:${{ github.event.inputs.image_tag }}|" task-definitions/quarkus-app-task.json

      - name: Replace Task Execution Role
        run: |
          sed -i "s|arn:aws:iam::020157571320:role/elkproject-ecs-task-execution-role|${{ secrets.ECS_TASK_EXECUTION_ROLE }}|" task-definitions/quarkus-app-task.json

      - name: Output Task Definition
        run: |
          cat task-definitions/quarkus-app-task.json

      - name: Register Task Definition
        run: |
          aws ecs register-task-definition --cli-input-json file://task-definitions/quarkus-app-task.json

      - name: Update ECS Service
        run: |
          aws ecs update-service \
            --cluster ${{ secrets.ECS_CLUSTER_NAME }} \
            --service-name elkproject-service \
            --task-definition elkproject \
            --force-new-deployment
