name: Infrastructure to PROD

on:
  push:
    branches:
      - prod

jobs:
  terraform:
    name: Deploy PROD Environment
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.4.0

      - name: Initialize Terraform
        working-directory: terraform/prod
        run: terraform init

      - name: Plan Terraform Changes
        working-directory: terraform/prod
        run: terraform plan -var-file=prod.tfvars

      - name: Apply Terraform Changes
        if: github.ref == 'refs/heads/prod'
        working-directory: terraform/prod
        run: terraform apply -auto-approve -var-file=prod.tfvars