name: Build and Push Kibana

on:
  push:
    paths:
      - kibana/**

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Get ECR Repository URL
        id: ecr
        run: |
          KIBANA_ECR_URL=$(terraform output -raw kibana_ecr_url)
          echo "KIBANA_ECR_URL=${KIBANA_ECR_URL}" >> $GITHUB_ENV

      - name: Log in to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and Tag Docker Image
        run: |
          docker build -t kibana ./kibana
          docker tag kibana:latest $KIBANA_ECR_URL:latest

      - name: Push to Amazon ECR
        run: |
          docker push $KIBANA_ECR_URL:latest
