name: Deploy Infrastructure

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::020157571320:role/github-actions-role
          aws-region: us-east-1

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      - name: Initialize Terraform
        working-directory: ./terraform
        run: terraform init

      - name: Validate Terraform
        working-directory: ./terraform
        run: terraform validate

      - name: Apply Terraform
        working-directory: ./terraform
        run: terraform apply -auto-approve

      - name: Build and Push Docker Images
        env:
          ECR_URI: ${{ secrets.ECR_URI }}
        run: |
          # Build and push Quarkus app image
          docker build -t $ECR_URI/quarkus-app:latest ./app
          docker push $ECR_URI/quarkus-app:latest
          
          # Build and push Vector image
          docker build -t $ECR_URI/vector:latest ./vector
          docker push $ECR_URI/vector:latest
          
          # Build and push Elasticsearch image
          docker build -t $ECR_URI/elasticsearch:latest ./elasticsearch
          docker push $ECR_URI/elasticsearch:latest
          
          # (Optional) Build and push Kibana image
          docker build -t $ECR_URI/kibana:latest ./kibana
          docker push $ECR_URI/kibana:latest
